### ISSUE TITLE
Making the API spec more RESTful

### ISSUE THREAD

**Issue by KevinStirling** [AbstractPlay/api#1]
Going over the [API Resource Model](https://www.abstractplay.com/wiki/api.resources), I've been noticing some aspects of it that don't really follow RESTful standards/ good practice. While its not a bad thing, i want to propose a redesign to prevent it from becoming bad over time.

For example, in /users/ there exists a /users/{id}, and a /users/me. The RESTful way to do this would be to have /users/{id} take care of both functionalities, and decide whether the id is ME on the server side, via OAuth2 access tokens and ids.

Another general rule is to have the nouns (in this case users, games, messages, etc) be the resources. Which is good here, but in places such as /users/{id}/games/following, should be something more like /users/{id}/games?filter=following. Or in the case of the pm's, /users/{id}/pm?status=unread

This will make things more slimmed down, with less endpoints. Working on a redesign now to propose...

**Comment by Perlkonig** [comment]
Thanks for this, @KevinStirling. The `/me` endpoint is a convenience for users who don't want to have to remember their numeric user id. I agree that it should simply redirect to the appropriate `/users/{id}` and the server should handle things from there. That's not how things currently work, but I will make the change. 

I agree, too, about incorporating query parameters.

Implementing GraphQL can potentially really clean up the API. If I'm sincere in my unspoken assumption that humans won't actually use the API directly (except for authentication), then it seems like I should do away with most of the endpoints and rely on GraphQL. I have to make sure I really understand how to do authentication properly with GraphQL before I start introducing mutations, though. So many freaking libraries!

**Comment by KevinStirling** [comment]
Ah i see, that makes more sense. Yeah a redirect is fine for that then, i misunderstood that.

I'm actually unfamiliar with GraphQL,but heres what I was working on over the weekend. Considering this to be a starting point, but i was thinking about building it out in Django this week and testing it on a local SQLite server:

**/users/**
**/users/{id}**
**/users/{id}/messages**
	-query params : 
?status=unread
	                          ?status=read 
	                          ?visibility=private


**/games** : All game types (not actually player instances of games)
**/games/{gameName}** : Info about the game type (undecided if it should be game name or game id in the path param)

I separated the challenges from the game types because i felt that games was become too confusing with them combined. here's what i came up with. In the DB there will be an association between the games table and the challenges table so that they can work together nicely.

**/challenges** : List of all challenges, 
      query params - 
?status=active , archive, pending
                                ?participants= {userId} (this will be for getting the list of challenges for the users profile)
                                ?turn= {userId} (for getting games where it is the logged in users name)
                                ?game={gameName} (or game id, for getting all challenges for a specific game type}

**/challenges/{challengeId}** : all data on a specific challenge

I think this covers a good amount of what you needs, aside for some of the stuff I didn't really understand such as the AI's, dev (which should be somewhat straight forward) and I need to look into the forms as well. 


Let me know what you think of this idea, I would be happy to build it out in Django, and eventually incorporate this GraphQL you speak of... looking at it now

**Comment by KevinStirling** [comment]
Hey @Perlkonig  just following up on the GraphQL topic, I've been looking into it. It seems cool, I was  initially considering using Django REST Framework to take care of the same stuff but it seems that Django REST is best suited for a mostly public API, and GraphQL seems to be the go to for having the API be consumed by your own website /clients. So either one I'm fine with just thought i'd let you know another good option. All depends on how you want to use the API though. It would be cool to allow the API to be used for mobile development too, just something i thought of randomly 😀

**Comment by KevinStirling** [comment]
reading more about GraphQL, and I'm realizing its not actually REST at all, GraphQL is a separate syntax for API's.. so now I must ask you the follow up question, do you want a REST API or GraphQL API ? I designed all the above endpoints with REST API in mind.

**Comment by Perlkonig** [comment]
The short answer is "I'm not sure." I may keep both for now since integrating the data into Graphene is trivial. The REST interface requires a lot more work to properly document (JSON schemas currently), but it's still helpful to do because it ensures I understand what I'm doing. You're right that they're very different approaches.

**Comment by KevinStirling** [comment]
Gotcha, well I can experiment with it as a REST framework like i designed for now, and if you want you could make separate branch for me to work in as I start to get the pieces together. It will be pretty basic since the direction isnt certain yet and this way we can just make a new branch if nessesary
